VERSION="2.2.1"

ACCOUNTS=[
"GAVKJUTEUK7JUUQFYNCIJOJVS4NSU63YCAGMUVTSMGUN5CA4XEEFIETQ",
"GBEI5MSYFGDTYBVLZZX6H2MOFHLDJ2IJZ3SQAQZE5YDEUAZJ5JWCF2IZ",
"GDA4Q3U44CVOA72CG6YQVD2UX7DUQL3GR5UHI2LMK5Y42RRLKFPZCBTC",
]

[DOCUMENTATION]
ORG_NAME="CashApp"
ORG_URL="https://www.capp-stellar.org/"
ORG_DESCRIPTION="Cash App is a mobile payment service available in the United States and the United Kingdom that allows users to transfer money to one another using a mobile phone app."
ORG_LOGO="https://www.capp-stellar.org/capp.png"


[[CURRENCIES]]
code="CAXLM"
status="live"
display_decimals=3
issuer="GAVKJUTEUK7JUUQFYNCIJOJVS4NSU63YCAGMUVTSMGUN5CA4XEEFIETQ"
anchor_asset_type="crypto"
name="CashApp XLM"
desc="Cash App, the pioneering digital payment platform, is here to revolutionize your investment game with its very own digital asset, CAXLM!"
image="https://www.capp-stellar.org/capp.png"

[[CURRENCIES]]
code="CXRP"
status="live"
display_decimals=3
issuer="GBEI5MSYFGDTYBVLZZX6H2MOFHLDJ2IJZ3SQAQZE5YDEUAZJ5JWCF2IZ"
anchor_asset_type="crypto"
name="CashApp XRP"
desc="Cash App, the pioneering digital payment platform, is here to revolutionize your investment game with its very own digital asset, CXRP!"
image="https://www.capp-stellar.org/cxrp.png"

[[CURRENCIES]]
code="CBTC"
status="live"
display_decimals=3
issuer="GDA4Q3U44CVOA72CG6YQVD2UX7DUQL3GR5UHI2LMK5Y42RRLKFPZCBTC"
anchor_asset_type="crypto"
name="CashApp BTC"
desc="Cash App, the pioneering digital payment platform, is here to revolutionize your investment game with its very own digital asset, CBTC!"
image="https://www.capp-stellar.org/cbtc.png"